### PR TITLE
Allow restoring of BinaryOpModels

### LINKED ISSUE #2301: [v4.17.1] cannot restore a saved session
I compiled and installed v4.17.1. I found that the new Sherpa cannot restore a saved session.
The session is not saved from a previous version of Sherpa.

```bash
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.30.0 -- An enhanced Interactive Python. Type '?' for help.
No event loop hook running.
Using matplotlib backend: agg

In [1]: from sherpa.astro import ui, xspec

In [2]: ui.restore('session.sherpa')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 ui.restore('session.sherpa')

File <string>:1, in restore(filename)

File ~/pylib/lib/python3.11/site-packages/sherpa/astro/ui/utils.py:532, in Session.restore(self, filename)
    483 def restore(self, filename='sherpa.save') -> None:
    484     """Load in a Sherpa session from a file.
    485
    486     .. warning::
   (...)
    530
    531     """
--> 532     super().restore(filename)
    533     if hasattr(sherpa.astro, "xspec"):
    534         if self._xspec_state is not None:

File ~/pylib/lib/python3.11/site-packages/sherpa/ui/utils.py:1287, in Session.restore(self, filename)
   1285 fin = open(filename, 'rb')
   1286 try:
-> 1287     obj = pickle.load(fin)
   1288 finally:
   1289     fin.close()

File ~/pylib/lib/python3.11/site-packages/sherpa/models/model.py:1622, in ArithmeticModel.__setstate__(self, state)
   1620 def __setstate__(self, state):
   1621     # In case old pickle files do not have cache info
-> 1622     self.cache_clear()
   1623     self.__dict__.update(state)

File ~/pylib/lib/python3.11/site-packages/sherpa/models/model.py:1267, in CompositeModel.cache_clear(self)
   1265 def cache_clear(self) -> None:
   1266     """Clear the cache for each component."""
-> 1267     for p in self.parts:
   1268         try:
   1269             p.cache_clear()

File ~/pylib/lib/python3.11/site-packages/sherpa/models/model.py:693, in Model.__getattr__(self, name)
    689         warnings.warn(wmsg, DeprecationWarning)
    691     return parameter
--> 693 NoNewAttributesAfterInit.__getattribute__(self, name)

AttributeError: 'BinaryOpModel' object has no attribute 'parts'
```

### PR DESCRIPTION
**Pull request by hamogu**
## Summary
Fix #2301 (can't read saved sessions which contain  compsite models)

## Details

`CompositeModel` (one of the parent classes of `BinaryOpModel`) gains an attribute `parts` in their `__init__` function. However, when they are restored from a pickeled save, `__init__` is never called. Eventually, the `parts` attribute is taken from the pickle and added to the objects dict, but we can't access it before that is done.

fixes #2301

I believe that this regression was introduced in #2166, but I did not actually bisect it because that didn't seem necessary after I understood what causes the problem.

This commit also adds tests for the regression and a minor syntax clean-up that helped me with interactive debugging.

## Rejected alternatives

Here, I'm taking the appraoch to do the least extra work possible and let Python do its thing. There are alternatives that handle the cache in a differnet way that could be chosen instead:

- Create the "parts" attribute before resetting the Cache in a way that respects the `NoAtrtibuteAfterInit` (e.g. by directly changing the `__dict__`
- Not include the cache in the pickle at all (reduces file size and risk of stale cache values when files are loaded into different versions of Sherpa, but throws away time if the cache is build with long computations)

Both options are somewhat more complex. It's just just 2-5 lines of code, but I'm afraid that it will introduce other corner cases that are hard to predict.

On the other hand, the approach in this PR has a higher risk of failing on pickles created with different versions of Sherpa (when the code for caching changes). I think that's OK - we don't guarantee that pickles work for different versions and we don't change that code often (just recently, but probably not again any time soon).

### CODE REVIEW

File: sherpa/astro/ui/tests/test_session_copy.py [hunk 1]
```diff
@@ -78,3 +80,29 @@ def test_save_restore(tmpdir):
     assert {1, } == set(session.list_data_ids())
     assert_array_equal(TEST, session.get_data(1).get_indep()[0])
     assert_array_equal(TEST2, session.get_data(1).get_dep())
+
+
+@requires_xspec
+def test_save_restore_composite_model_with_cache(tmpdir):
+    """Test that the save/restore works with a composite model.
+
+    Specifically, we use a model form XSPEC that has a cache.
```
[the remark this answers is not in the document]
Comment (DougBurke) [reply sherpa/astro/ui/tests/test_session_copy.py:89]: ... I assume.

File: sherpa/models/model.py [hunk 2]
```diff
@@ -1617,11 +1617,6 @@ def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
                                  strformat=strformat)
         return NotImplemented
 
-    def __setstate__(self, state):
```
Comment (DougBurke) [inline sherpa/models/model.py:1620]: Ugh. Multiple Inheritance not for the win !

**Comment by hamogu** [comment]
I implemented the suggested changes locally to make sure I check and run the test before firing up the CI. I also took the opportunity to rebase on main; only there last commit is new, the others just have a new hash because it's rebased.

**Review by DougBurke — APPROVED** [review]
It's been on my back burner to add better tests of `save` / `restore`, so this is a start. I do wonder if we want to have the output from previous versions (either in `sherpa` or `sherpa-test-data`) that we can use to verify whether we can still read in old versions, but that's for a different issue.
