### ISSUE TITLE
issue with arf.get_x() and EvaluationSpace1D

### ISSUE THREAD

**Issue by danhoak** [sherpa/sherpa#572]
Hi,

I recently upgraded to 4.10.1 from 4.10.0, and noticed a new error when trying to get the array of energies over which my ARF is defined.  The code looks like this:

```
import sherpa
sherpa.load_arf(1, "rexARF1.fits")
sherpa.load_arf(1, "rexARF_flat.fits", resp_id=2)
arf1 = sherpa.get_arf(1,1)
arf_x = arf1.get_x()
```

The error is this:

Traceback (most recent call last):
  File "fit_spec_use_linemodule.py", line 186, in <module>
    arf_x = arf1.get_x()
  File "/n/home11/dhoak/.conda/envs/test/lib/python2.7/site-packages/sherpa/data.py", line 741, in get_x
    indep = self._get_x_space(filter, model, use_evaluation_space)
  File "/n/home11/dhoak/.conda/envs/test/lib/python2.7/site-packages/sherpa/data.py", line 612, in _get_x_space
    data_space = self._get_data_space(filter)
  File "/n/home11/dhoak/.conda/envs/test/lib/python2.7/site-packages/sherpa/data.py", line 738, in _get_data_space
    return EvaluationSpace1D(self.xlo, self.xhi)
AttributeError: 'DataARF' object has no attribute 'xlo'

I have attached the ARF file (with a .txt extension because github doesn't accept .fits files), in case it is a problem with the way I've formatted that file.  Many thanks for any help!

[rexARF1.fits.txt](https://github.com/sherpa/sherpa/files/2673593/rexARF1.fits.txt)

Cheers,

 - Dan

**Comment by olaurino** [comment]
@danhoak sorry for the regression. I'll look into it ASAP. Would anything prevent you from staying with 4.10.0 for the short term until we fix this issue?

**Comment by danhoak** [comment]
Hi Omar - working with 4.10.0 is perfectly fine for me.  Just wanted to
give you a heads up about a potential bug (or, see if I'm building my ARF
files incorrectly...)

Cheers,

 - Dan

**Comment by olaurino** [comment]
@danhoak I can reproduce the issue with one of our test ARFs, so it does not look like an "operator error".

**Comment by DougBurke** [comment]
I honestly have no idea how `get_x` / `get_x0` / ... and `get_indep` are meant to interact.

It looks like - using CIAO 4.10 - that `get_x` is returning the mid-point of the bin: that is

```
sherpa-1> a1 = unpack_arf('obs1.arf')
sherpa-2> x = a1.get_x()
sherpa-3> deps = a1.get_indep()
sherpa-4> dlo = deps[0]
sherpa-5> dhi = deps[1]
sherpa-6> dmid = (dlo + dhi) / 2
sherpa-7> (x == dmid).all()
          True
sherpa-8> dmid[0:10]
           
array([ 0.225     ,  0.235     ,  0.245     ,  0.255     ,  0.265     ,
        0.27500001,  0.285     ,  0.295     ,  0.30500001,  0.315     ])
```

Using master branch `get_x` fails but `get_dep` still works, so you can try using that @danhoak 

```
herpa In [1]: a1 = unpack_arf('obs1.arf')

sherpa In [2]: x = a1.get_x()
AttributeError: 'DataARF' object has no attribute 'xlo'

sherpa In [3]: deps = a1.get_indep()

sherpa In [4]: dlo = deps[0]

sherpa In [5]: dhi = deps[1]

sherpa In [6]: dmid = (dlo + dhi) / 2

sherpa In [7]: dmid[0:10]
Out[7]: 
array([ 0.225     ,  0.235     ,  0.245     ,  0.255     ,  0.265     ,
        0.27500001,  0.285     ,  0.295     ,  0.30500001,  0.315     ])

```

**Comment by olaurino** [comment]
I should have a fix. I'll issue a PR tomorrow after making sure I add some baseline data to the tests. Also, I think the RMF class will need the same fix.

Doug already provided the best workaround I can think of.
